name: Deploy theme to dev.rytkoset.net

on:
  push:
    branches:
      - dev
    paths:
      - 'wp-content/themes/rytkoset-theme/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@110f9186c050f71550953127052e77650219c287 # v4.4.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftps
          local-dir: wp-content/themes/rytkoset-theme/
          server-dir: /wp-content/themes/rytkoset-theme/
          log-level: standard
          dangerous-clean-slate: false
